# Frontend Dockerfile for development

FROM node:latest

RUN corepack enable

WORKDIR /app

COPY pnpm-workspace.yaml ../pnpm-workspace.yaml
COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 5173

CMD ["pnpm", "run", "dev"]