# Production Docker Compose configuration
# docker-compose -f docker-compose.yml up --build -d

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL_PROD}
      PORT: 4000
      # Spotify credentials
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CLIENT_ORIGIN: ${CLIENT_ORIGIN}
      NODE_ENV: production
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: always
    ports:
      - "8080:80"
    environment:
      VITE_API_URL: ${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:

volumes:
  pgdata:
