import { ExtractedColor } from "@shared/types";
import { useMemo } from "react";

/**
 * The props for the BlurryHeader component.
 */
interface BlobBackgroundProps {
  /*** The colors to use for the blobs */
  _colors?: ExtractedColor[];
  /*** The children to render on top of the blobs */
  children?: React.ReactNode;
}

/**
 *
 * The blobs are randomly generated on mount and have different sizes, colors, and animations.
 * They are created using div elements with a blur filter and a random size, color, and position.
 * The blobs are either generated by the extract-colors package or are chosen by the user.
 */

/**
 * This component creates a header with a blurry background effect using blobs.
 * @param {ExtractedColor[] | undefined} colors The colors to use for the blobs, defaults to black
 * @param {React.ReactNode} children The children to render on top of the blobs
 */
const BlurryHeader = ({ _colors, children }: BlobBackgroundProps) => {
  const defaultColors: ExtractedColor[] = [{ hex: "#00ffff" }];
  const colors = _colors && _colors.length > 0 ? _colors : defaultColors;

  // Total number of blobs, previously 40 but
  // reduced to 30 after adding ViewTransitions.
  // Was causing a flicker on navigation.
  const totalBlobs = 30;
  const colorCount = colors.length;

  // Generate blobs with proportional color distribution
  const blobs = useMemo(() => {
    const blobsArray = [];
    for (let i = 0; i < colorCount; i++) {
      const blobCount = Math.round((totalBlobs / colorCount) * (colorCount - i)); // More for first colors
      for (let j = 0; j < blobCount; j++) {
        blobsArray.push({
          size: Math.floor(Math.random() * 300) + 200,
          top: Math.random() * 100,
          left: Math.random() * 100,
          color: colors[i].hex,
          blur: Math.floor(Math.random() * 60) + 80,
          animationClass: `animate-lava${j % 3}`,
        });
      }
    }
    return blobsArray;
  }, [colorCount, colors]);

  return (
    <div className="relative w-full h-[500px] pb-28 overflow-hidden bg-gradient-to-b from-black/0 via-neutral-900/10 to-neutral-900">
      {blobs.map((blob, index) => (
        <div
          key={index}
          className={`absolute rounded-full -z-[5] ${blob.animationClass}`}
          style={{
            width: `${blob.size}px`,
            height: `${blob.size}px`,
            top: `${blob.top}%`,
            left: `${blob.left}%`,
            filter: `blur(${blob.blur}px)`,
            backgroundColor: blob.color,
          }}
        ></div>
      ))}
      {children}
    </div>
  );
};

export default BlurryHeader;
