export const mockReviewData = {
  album: {
    album_type: "album",
    total_tracks: 16,
    available_markets: ["AR"],
    external_urls: {
      spotify: "https://open.spotify.com/album/0JGOiO34nwfUdDrD612dOp",
    },
    href: "https://api.spotify.com/v1/albums/0JGOiO34nwfUdDrD612dOp?locale=en-IE%2Cen-GB%3Bq%3D0.9%2Cen-US%3Bq%3D0.8%2Cen%3Bq%3D0.7",
    id: "0JGOiO34nwfUdDrD612dOp",
    images: [
      {
        url: "https://i.scdn.co/image/ab67616d0000b2732a038d3bf875d23e4aeaa84e",
        height: 640,
        width: 640,
      },
      {
        url: "https://i.scdn.co/image/ab67616d00001e022a038d3bf875d23e4aeaa84e",
        height: 300,
        width: 300,
      },
      {
        url: "https://i.scdn.co/image/ab67616d000048512a038d3bf875d23e4aeaa84e",
        height: 64,
        width: 64,
      },
    ],
    name: "Happier Than Ever",
    release_date: "2021-07-30",
    release_date_precision: "day",
    type: "album",
    uri: "spotify:album:0JGOiO34nwfUdDrD612dOp",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH",
        },
        href: "https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH",
        id: "6qqNVTkY8uBg9cP3Jd7DAH",
        name: "Billie Eilish",
        type: "artist",
        uri: "spotify:artist:6qqNVTkY8uBg9cP3Jd7DAH",
      },
    ],
    tracks: {
      href: "https://api.spotify.com/v1/albums/0JGOiO34nwfUdDrD612dOp/tracks?offset=0&limit=50&locale=en-IE,en-GB;q%3D0.9,en-US;q%3D0.8,en;q%3D0.7",
      limit: 50,
      next: null,
      offset: 0,
      previous: null,
      total: 16,
      items: [
        {
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH",
              },
              href: "https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH",
              id: "6qqNVTkY8uBg9cP3Jd7DAH",
              name: "Billie Eilish",
              type: "artist",
              uri: "spotify:artist:6qqNVTkY8uBg9cP3Jd7DAH",
            },
          ],
          available_markets: ["AR"],
          disc_number: 1,
          duration_ms: 244221,
          explicit: false,
          external_urls: {
            spotify: "https://open.spotify.com/track/4HOryCnbme0zBnF8LWij3f",
          },
          href: "https://api.spotify.com/v1/tracks/4HOryCnbme0zBnF8LWij3f",
          id: "4HOryCnbme0zBnF8LWij3f",
          name: "Getting Older",
          preview_url: null,
          track_number: 1,
          type: "track",
          uri: "spotify:track:4HOryCnbme0zBnF8LWij3f",
          is_local: false,
        },
        {
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH",
              },
              href: "https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH",
              id: "6qqNVTkY8uBg9cP3Jd7DAH",
              name: "Billie Eilish",
              type: "artist",
              uri: "spotify:artist:6qqNVTkY8uBg9cP3Jd7DAH",
            },
          ],
          available_markets: ["AR"],
          disc_number: 1,
          duration_ms: 158463,
          explicit: true,
          external_urls: {
            spotify: "https://open.spotify.com/track/7bcy34fBT2ap1L4bfPsl9q",
          },
          href: "https://api.spotify.com/v1/tracks/7bcy34fBT2ap1L4bfPsl9q",
          id: "7bcy34fBT2ap1L4bfPsl9q",
          name: "I Didn't Change My Number",
          preview_url: null,
          track_number: 2,
          type: "track",
          uri: "spotify:track:7bcy34fBT2ap1L4bfPsl9q",
          is_local: false,
        },
        {
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH",
              },
              href: "https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH",
              id: "6qqNVTkY8uBg9cP3Jd7DAH",
              name: "Billie Eilish",
              type: "artist",
              uri: "spotify:artist:6qqNVTkY8uBg9cP3Jd7DAH",
            },
          ],
          available_markets: ["AR"],
          disc_number: 1,
          duration_ms: 196730,
          explicit: false,
          external_urls: {
            spotify: "https://open.spotify.com/track/2KnuaZYoGzDoHiBTNYOTXG",
          },
          href: "https://api.spotify.com/v1/tracks/2KnuaZYoGzDoHiBTNYOTXG",
          id: "2KnuaZYoGzDoHiBTNYOTXG",
          name: "Billie Bossa Nova",
          preview_url: null,
          track_number: 3,
          type: "track",
          uri: "spotify:track:2KnuaZYoGzDoHiBTNYOTXG",
          is_local: false,
        },
        {
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH",
              },
              href: "https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH",
              id: "6qqNVTkY8uBg9cP3Jd7DAH",
              name: "Billie Eilish",
              type: "artist",
              uri: "spotify:artist:6qqNVTkY8uBg9cP3Jd7DAH",
            },
          ],
          available_markets: ["AR"],
          disc_number: 1,
          duration_ms: 210005,
          explicit: false,
          external_urls: {
            spotify: "https://open.spotify.com/track/3YUMWmx8EJq0DurfuIwoGh",
          },
          href: "https://api.spotify.com/v1/tracks/3YUMWmx8EJq0DurfuIwoGh",
          id: "3YUMWmx8EJq0DurfuIwoGh",
          name: "my future",
          preview_url: null,
          track_number: 4,
          type: "track",
          uri: "spotify:track:3YUMWmx8EJq0DurfuIwoGh",
          is_local: false,
        },
        {
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH",
              },
              href: "https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH",
              id: "6qqNVTkY8uBg9cP3Jd7DAH",
              name: "Billie Eilish",
              type: "artist",
              uri: "spotify:artist:6qqNVTkY8uBg9cP3Jd7DAH",
            },
          ],
          available_markets: ["AR"],
          disc_number: 1,
          duration_ms: 210232,
          explicit: false,
          external_urls: {
            spotify: "https://open.spotify.com/track/4t2OeILB07eMGTXSUbMPEu",
          },
          href: "https://api.spotify.com/v1/tracks/4t2OeILB07eMGTXSUbMPEu",
          id: "4t2OeILB07eMGTXSUbMPEu",
          name: "Oxytocin",
          preview_url: null,
          track_number: 5,
          type: "track",
          uri: "spotify:track:4t2OeILB07eMGTXSUbMPEu",
          is_local: false,
        },
        {
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH",
              },
              href: "https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH",
              id: "6qqNVTkY8uBg9cP3Jd7DAH",
              name: "Billie Eilish",
              type: "artist",
              uri: "spotify:artist:6qqNVTkY8uBg9cP3Jd7DAH",
            },
          ],
          available_markets: ["AR"],
          disc_number: 1,
          duration_ms: 151536,
          explicit: false,
          external_urls: {
            spotify: "https://open.spotify.com/track/0FfqyjhB6Kspvit1oOo7ax",
          },
          href: "https://api.spotify.com/v1/tracks/0FfqyjhB6Kspvit1oOo7ax",
          id: "0FfqyjhB6Kspvit1oOo7ax",
          name: "GOLDWING",
          preview_url: null,
          track_number: 6,
          type: "track",
          uri: "spotify:track:0FfqyjhB6Kspvit1oOo7ax",
          is_local: false,
        },
        {
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH",
              },
              href: "https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH",
              id: "6qqNVTkY8uBg9cP3Jd7DAH",
              name: "Billie Eilish",
              type: "artist",
              uri: "spotify:artist:6qqNVTkY8uBg9cP3Jd7DAH",
            },
          ],
          available_markets: ["AR"],
          disc_number: 1,
          duration_ms: 212496,
          explicit: true,
          external_urls: {
            spotify: "https://open.spotify.com/track/4191RXFPa7Ge9XkA4cWlna",
          },
          href: "https://api.spotify.com/v1/tracks/4191RXFPa7Ge9XkA4cWlna",
          id: "4191RXFPa7Ge9XkA4cWlna",
          name: "Lost Cause",
          preview_url: null,
          track_number: 7,
          type: "track",
          uri: "spotify:track:4191RXFPa7Ge9XkA4cWlna",
          is_local: false,
        },
        {
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH",
              },
              href: "https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH",
              id: "6qqNVTkY8uBg9cP3Jd7DAH",
              name: "Billie Eilish",
              type: "artist",
              uri: "spotify:artist:6qqNVTkY8uBg9cP3Jd7DAH",
            },
          ],
          available_markets: ["AR"],
          disc_number: 1,
          duration_ms: 234761,
          explicit: false,
          external_urls: {
            spotify: "https://open.spotify.com/track/5XsAal7ZcWg1I5T4NcRjkv",
          },
          href: "https://api.spotify.com/v1/tracks/5XsAal7ZcWg1I5T4NcRjkv",
          id: "5XsAal7ZcWg1I5T4NcRjkv",
          name: "Halley's Comet",
          preview_url: null,
          track_number: 8,
          type: "track",
          uri: "spotify:track:5XsAal7ZcWg1I5T4NcRjkv",
          is_local: false,
        },
        {
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH",
              },
              href: "https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH",
              id: "6qqNVTkY8uBg9cP3Jd7DAH",
              name: "Billie Eilish",
              type: "artist",
              uri: "spotify:artist:6qqNVTkY8uBg9cP3Jd7DAH",
            },
          ],
          available_markets: ["AR"],
          disc_number: 1,
          duration_ms: 227679,
          explicit: false,
          external_urls: {
            spotify: "https://open.spotify.com/track/4T2zre0jqstNJ5Gt0WG9lz",
          },
          href: "https://api.spotify.com/v1/tracks/4T2zre0jqstNJ5Gt0WG9lz",
          id: "4T2zre0jqstNJ5Gt0WG9lz",
          name: "Not My Responsibility",
          preview_url: null,
          track_number: 9,
          type: "track",
          uri: "spotify:track:4T2zre0jqstNJ5Gt0WG9lz",
          is_local: false,
        },
        {
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH",
              },
              href: "https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH",
              id: "6qqNVTkY8uBg9cP3Jd7DAH",
              name: "Billie Eilish",
              type: "artist",
              uri: "spotify:artist:6qqNVTkY8uBg9cP3Jd7DAH",
            },
          ],
          available_markets: ["AR"],
          disc_number: 1,
          duration_ms: 214058,
          explicit: true,
          external_urls: {
            spotify: "https://open.spotify.com/track/5uSG6fUPRaehaV820zcpsK",
          },
          href: "https://api.spotify.com/v1/tracks/5uSG6fUPRaehaV820zcpsK",
          id: "5uSG6fUPRaehaV820zcpsK",
          name: "OverHeated",
          preview_url: null,
          track_number: 10,
          type: "track",
          uri: "spotify:track:5uSG6fUPRaehaV820zcpsK",
          is_local: false,
        },
        {
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH",
              },
              href: "https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH",
              id: "6qqNVTkY8uBg9cP3Jd7DAH",
              name: "Billie Eilish",
              type: "artist",
              uri: "spotify:artist:6qqNVTkY8uBg9cP3Jd7DAH",
            },
          ],
          available_markets: ["AR"],
          disc_number: 1,
          duration_ms: 206622,
          explicit: false,
          external_urls: {
            spotify: "https://open.spotify.com/track/5jhBwnqzNNrENXnYrAdoCe",
          },
          href: "https://api.spotify.com/v1/tracks/5jhBwnqzNNrENXnYrAdoCe",
          id: "5jhBwnqzNNrENXnYrAdoCe",
          name: "Everybody Dies",
          preview_url: null,
          track_number: 11,
          type: "track",
          uri: "spotify:track:5jhBwnqzNNrENXnYrAdoCe",
          is_local: false,
        },
        {
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH",
              },
              href: "https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH",
              id: "6qqNVTkY8uBg9cP3Jd7DAH",
              name: "Billie Eilish",
              type: "artist",
              uri: "spotify:artist:6qqNVTkY8uBg9cP3Jd7DAH",
            },
          ],
          available_markets: ["AR"],
          disc_number: 1,
          duration_ms: 245896,
          explicit: false,
          external_urls: {
            spotify: "https://open.spotify.com/track/042Sl6Mn83JHyLEqdK7uI0",
          },
          href: "https://api.spotify.com/v1/tracks/042Sl6Mn83JHyLEqdK7uI0",
          id: "042Sl6Mn83JHyLEqdK7uI0",
          name: "Your Power",
          preview_url: null,
          track_number: 12,
          type: "track",
          uri: "spotify:track:042Sl6Mn83JHyLEqdK7uI0",
          is_local: false,
        },
        {
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH",
              },
              href: "https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH",
              id: "6qqNVTkY8uBg9cP3Jd7DAH",
              name: "Billie Eilish",
              type: "artist",
              uri: "spotify:artist:6qqNVTkY8uBg9cP3Jd7DAH",
            },
          ],
          available_markets: ["AR"],
          disc_number: 1,
          duration_ms: 195776,
          explicit: true,
          external_urls: {
            spotify: "https://open.spotify.com/track/38GBNKZUhfBkk3oNlWzRYd",
          },
          href: "https://api.spotify.com/v1/tracks/38GBNKZUhfBkk3oNlWzRYd",
          id: "38GBNKZUhfBkk3oNlWzRYd",
          name: "NDA",
          preview_url: null,
          track_number: 13,
          type: "track",
          uri: "spotify:track:38GBNKZUhfBkk3oNlWzRYd",
          is_local: false,
        },
        {
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH",
              },
              href: "https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH",
              id: "6qqNVTkY8uBg9cP3Jd7DAH",
              name: "Billie Eilish",
              type: "artist",
              uri: "spotify:artist:6qqNVTkY8uBg9cP3Jd7DAH",
            },
          ],
          available_markets: ["AR"],
          disc_number: 1,
          duration_ms: 173539,
          explicit: false,
          external_urls: {
            spotify: "https://open.spotify.com/track/20R4HfKloPKgXDqU7UKk3x",
          },
          href: "https://api.spotify.com/v1/tracks/20R4HfKloPKgXDqU7UKk3x",
          id: "20R4HfKloPKgXDqU7UKk3x",
          name: "Therefore I Am",
          preview_url: null,
          track_number: 14,
          type: "track",
          uri: "spotify:track:20R4HfKloPKgXDqU7UKk3x",
          is_local: false,
        },
        {
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH",
              },
              href: "https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH",
              id: "6qqNVTkY8uBg9cP3Jd7DAH",
              name: "Billie Eilish",
              type: "artist",
              uri: "spotify:artist:6qqNVTkY8uBg9cP3Jd7DAH",
            },
          ],
          available_markets: ["AR"],
          disc_number: 1,
          duration_ms: 298899,
          explicit: true,
          external_urls: {
            spotify: "https://open.spotify.com/track/4RVwu0g32PAqgUiJoXsdF8",
          },
          href: "https://api.spotify.com/v1/tracks/4RVwu0g32PAqgUiJoXsdF8",
          id: "4RVwu0g32PAqgUiJoXsdF8",
          name: "Happier Than Ever",
          preview_url: null,
          track_number: 15,
          type: "track",
          uri: "spotify:track:4RVwu0g32PAqgUiJoXsdF8",
          is_local: false,
        },
        {
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH",
              },
              href: "https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH",
              id: "6qqNVTkY8uBg9cP3Jd7DAH",
              name: "Billie Eilish",
              type: "artist",
              uri: "spotify:artist:6qqNVTkY8uBg9cP3Jd7DAH",
            },
          ],
          available_markets: ["AR"],
          disc_number: 1,
          duration_ms: 194886,
          explicit: false,
          external_urls: {
            spotify: "https://open.spotify.com/track/4ak9GGe6afmi2HbxEjvhIC",
          },
          href: "https://api.spotify.com/v1/tracks/4ak9GGe6afmi2HbxEjvhIC",
          id: "4ak9GGe6afmi2HbxEjvhIC",
          name: "Male Fantasy",
          preview_url: null,
          track_number: 16,
          type: "track",
          uri: "spotify:track:4ak9GGe6afmi2HbxEjvhIC",
          is_local: false,
        },
      ],
    },
    copyrights: [
      {
        text: "© 2021 Darkroom/Interscope Records",
        type: "C",
      },
      {
        text: "℗ 2021 Darkroom/Interscope Records",
        type: "P",
      },
    ],
    external_ids: {
      upc: "00602438247707",
    },
    genres: [],
    label: "Darkroom/Interscope Records",
    popularity: 82,
  },
  ratedTracks: [
    {
      spotifyID: "4HOryCnbme0zBnF8LWij3f",
      rating: 0,
    },
    {
      spotifyID: "7bcy34fBT2ap1L4bfPsl9q",
      rating: 8,
    },
    {
      spotifyID: "2KnuaZYoGzDoHiBTNYOTXG",
      rating: 8,
    },
    {
      spotifyID: "3YUMWmx8EJq0DurfuIwoGh",
      rating: 7,
    },
    {
      spotifyID: "4t2OeILB07eMGTXSUbMPEu",
      rating: 0,
    },
    {
      spotifyID: "0FfqyjhB6Kspvit1oOo7ax",
      rating: 2,
    },
    {
      spotifyID: "4191RXFPa7Ge9XkA4cWlna",
      rating: 6,
    },
    {
      spotifyID: "5XsAal7ZcWg1I5T4NcRjkv",
      rating: 4,
    },
    {
      spotifyID: "4T2zre0jqstNJ5Gt0WG9lz",
      rating: 3,
    },
    {
      spotifyID: "5uSG6fUPRaehaV820zcpsK",
      rating: 8,
    },
    {
      spotifyID: "5jhBwnqzNNrENXnYrAdoCe",
      rating: 1,
    },
    {
      spotifyID: "042Sl6Mn83JHyLEqdK7uI0",
      rating: 7,
    },
    {
      spotifyID: "38GBNKZUhfBkk3oNlWzRYd",
      rating: 2,
    },
    {
      spotifyID: "20R4HfKloPKgXDqU7UKk3x",
      rating: 8,
    },
    {
      spotifyID: "4RVwu0g32PAqgUiJoXsdF8",
      rating: 9,
    },
    {
      spotifyID: "4ak9GGe6afmi2HbxEjvhIC",
      rating: 7,
    },
  ],
  bestSong: "2",
  worstSong: "3",
  reviewContent: "Amazing album with deep emotions.",
};
