// Generated by db:capture-fixtures, do not edit by hand
import type { CapturedAlbum } from "./captured";

export const capturedAlbums: CapturedAlbum[] = [
  {
    "spotifyID": "7aJuG4TFXa2hmE4z1yxc3n",
    "name": "HIT ME HARD AND SOFT",
    "uri": "spotify:album:7aJuG4TFXa2hmE4z1yxc3n",
    "rawReleaseDate": "2024-05-17",
    "releaseDate": "May 17th, 2024",
    "releaseYear": 2024,
    "runtime": "43 minutes 50 seconds",
    "imageURLs": [
      {
        "url": "https://i.scdn.co/image/ab67616d0000b27371d62ea7ea8a5be92d3c1f62",
        "height": 640,
        "width": 640
      },
      {
        "url": "https://i.scdn.co/image/ab67616d00001e0271d62ea7ea8a5be92d3c1f62",
        "height": 300,
        "width": 300
      },
      {
        "url": "https://i.scdn.co/image/ab67616d0000485171d62ea7ea8a5be92d3c1f62",
        "height": 64,
        "width": 64
      }
    ],
    "colors": [
      {
        "hex": "#0b3859"
      },
      {
        "hex": "#adafa0"
      }
    ],
    "artists": [
      {
        "spotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "name": "Billie Eilish",
        "imageURLs": [
          {
            "url": "https://i.scdn.co/image/ab6761610000e5eb4a21b4760d2ecb7b0dcdc8da",
            "height": 640,
            "width": 640
          },
          {
            "url": "https://i.scdn.co/image/ab676161000051744a21b4760d2ecb7b0dcdc8da",
            "height": 320,
            "width": 320
          },
          {
            "url": "https://i.scdn.co/image/ab6761610000f1784a21b4760d2ecb7b0dcdc8da",
            "height": 160,
            "width": 160
          }
        ]
      }
    ],
    "tracks": [
      {
        "spotifyID": "1CsMKhwEmNnmvHUuO5nryA",
        "name": "SKINNY",
        "duration": 219733,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "629DixmZGHc7ILtEntuiWE",
        "name": "LUNCH",
        "duration": 179586,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "7BRD7x5pt8Lqa1eGYC4dzj",
        "name": "CHIHIRO",
        "duration": 303440,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "6dOtVTDdiauQNBQEDOtlAB",
        "name": "BIRDS OF A FEATHER",
        "duration": 210373,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "3QaPy1KgI7nu9FJEQUgn6h",
        "name": "WILDFLOWER",
        "duration": 261466,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "6TGd66r0nlPaYm3KIoI7ET",
        "name": "THE GREATEST",
        "duration": 293840,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "6fPan2saHdFaIHuTSatORv",
        "name": "L’AMOUR DE MA VIE",
        "duration": 333986,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "1LLUoftvmTjVNBHZoQyveF",
        "name": "THE DINER",
        "duration": 186346,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "7DpUoxGSdlDHfqCYj0otzU",
        "name": "BITTERSUITE",
        "duration": 298440,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "2prqm9sPLj10B4Wg0wE5x9",
        "name": "BLUE",
        "duration": 343120,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      }
    ]
  },
  {
    "spotifyID": "3HHNR44YbP7XogMVwzbodx",
    "name": "Twelve Carat Toothache",
    "uri": "spotify:album:3HHNR44YbP7XogMVwzbodx",
    "rawReleaseDate": "2022-06-03",
    "releaseDate": "June 3rd, 2022",
    "releaseYear": 2022,
    "runtime": "43 minutes 18 seconds",
    "imageURLs": [
      {
        "url": "https://i.scdn.co/image/ab67616d0000b27334362676667a4322838ccc97",
        "height": 640,
        "width": 640
      },
      {
        "url": "https://i.scdn.co/image/ab67616d00001e0234362676667a4322838ccc97",
        "height": 300,
        "width": 300
      },
      {
        "url": "https://i.scdn.co/image/ab67616d0000485134362676667a4322838ccc97",
        "height": 64,
        "width": 64
      }
    ],
    "colors": [
      {
        "hex": "#404147"
      },
      {
        "hex": "#cfcfcf"
      }
    ],
    "artists": [
      {
        "spotifyID": "246dkjvS1zLTtiykXe5h60",
        "name": "Post Malone",
        "imageURLs": [
          {
            "url": "https://i.scdn.co/image/ab6761610000e5ebe17c0aa1714a03d62b5ce4e0",
            "height": 640,
            "width": 640
          },
          {
            "url": "https://i.scdn.co/image/ab67616100005174e17c0aa1714a03d62b5ce4e0",
            "height": 320,
            "width": 320
          },
          {
            "url": "https://i.scdn.co/image/ab6761610000f178e17c0aa1714a03d62b5ce4e0",
            "height": 160,
            "width": 160
          }
        ]
      }
    ],
    "tracks": [
      {
        "spotifyID": "67dU06KGaJHLLlo5Y5bkD2",
        "name": "Reputation",
        "duration": 248177,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "32vE1nuG8T9c8bhmZdRY6d",
        "name": "Cooped Up (with Roddy Ricch)",
        "duration": 185857,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": [
          {
            "id": "757aE44tKEUQEqRuT6GnEB",
            "name": "Roddy Ricch"
          }
        ]
      },
      {
        "spotifyID": "1NvpO1o8SpkdH3txtJQQc7",
        "name": "Lemon Tree",
        "duration": 243486,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "6Kfoo60npYPdvNxMPMiDpX",
        "name": "Wrapped Around Your Finger",
        "duration": 193565,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "0O6u0VJ46W86TxN9wgyqDj",
        "name": "I Like You (A Happier Song) (with Doja Cat)",
        "duration": 192840,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": [
          {
            "id": "5cj0lLjcoR7YOSnhnX0Po5",
            "name": "Doja Cat"
          }
        ]
      },
      {
        "spotifyID": "4IxeKzzxUSEgivgtbSbyIK",
        "name": "I Cannot Be (A Sadder Song) (with Gunna)",
        "duration": 169824,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": [
          {
            "id": "2hlmm7s2ICUX0LVIhVFlZQ",
            "name": "Gunna"
          }
        ]
      },
      {
        "spotifyID": "2meHtZ7N97pJfvTL4hYtfv",
        "name": "Insane",
        "duration": 169660,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "6R9c642Hs3tOdLowjYaWt2",
        "name": "Love/Hate Letter To Alcohol (with Fleet Foxes)",
        "duration": 183816,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": [
          {
            "id": "4EVpmkEwrLYEg6jIsiPMIb",
            "name": "Fleet Foxes"
          }
        ]
      },
      {
        "spotifyID": "2OcSE0EXzgUuqkM1NIJPHJ",
        "name": "Wasting Angels (with The Kid LAROI)",
        "duration": 243158,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": [
          {
            "id": "2tIP7SsRs7vjIcLrU85W8J",
            "name": "The Kid LAROI"
          }
        ]
      },
      {
        "spotifyID": "7JyFwJC3uRpiNfq7oKafgn",
        "name": "Euthanasia",
        "duration": 145795,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "5Ja2u1FPlVxrxeMWEa2dcn",
        "name": "When I’m Alone",
        "duration": 195110,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "2GUSz3vtf8jhVXri1CTrQX",
        "name": "Waiting For A Miracle",
        "duration": 141851,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "1nltpRhEiXikwDlVn4UADk",
        "name": "One Right Now (with The Weeknd)",
        "duration": 192721,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": [
          {
            "id": "1Xyo4u8uXC1ZmMpatF05PJ",
            "name": "The Weeknd"
          }
        ]
      },
      {
        "spotifyID": "0lmRKkc33g1N9fWW9nZPVc",
        "name": "New Recording 12, Jan 3, 2020",
        "duration": 92718,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      }
    ]
  },
  {
    "spotifyID": "2ODvWsOgouMbaA5xf0RkJe",
    "name": "Starboy",
    "uri": "spotify:album:2ODvWsOgouMbaA5xf0RkJe",
    "rawReleaseDate": "2016-11-25",
    "releaseDate": "November 25th, 2016",
    "releaseYear": 2016,
    "runtime": "68 minutes 36 seconds",
    "imageURLs": [
      {
        "url": "https://i.scdn.co/image/ab67616d0000b2734718e2b124f79258be7bc452",
        "height": 640,
        "width": 640
      },
      {
        "url": "https://i.scdn.co/image/ab67616d00001e024718e2b124f79258be7bc452",
        "height": 300,
        "width": 300
      },
      {
        "url": "https://i.scdn.co/image/ab67616d000048514718e2b124f79258be7bc452",
        "height": 64,
        "width": 64
      }
    ],
    "colors": [
      {
        "hex": "#54e4d6"
      },
      {
        "hex": "#ebbc06"
      },
      {
        "hex": "#051447"
      }
    ],
    "artists": [
      {
        "spotifyID": "1Xyo4u8uXC1ZmMpatF05PJ",
        "name": "The Weeknd",
        "imageURLs": [
          {
            "url": "https://i.scdn.co/image/ab6761610000e5ebc1719ac9e6a75c1c25835018",
            "height": 640,
            "width": 640
          },
          {
            "url": "https://i.scdn.co/image/ab67616100005174c1719ac9e6a75c1c25835018",
            "height": 320,
            "width": 320
          },
          {
            "url": "https://i.scdn.co/image/ab6761610000f178c1719ac9e6a75c1c25835018",
            "height": 160,
            "width": 160
          }
        ]
      }
    ],
    "tracks": [
      {
        "spotifyID": "7MXVkk9YMctZqd1Srtv4MB",
        "name": "Starboy",
        "duration": 230453,
        "artistName": "The Weeknd",
        "artistSpotifyID": "1Xyo4u8uXC1ZmMpatF05PJ",
        "features": [
          {
            "id": "4tZwfgrHOc3mvqYlEYSvVi",
            "name": "Daft Punk"
          }
        ]
      },
      {
        "spotifyID": "4F7A0DXBrmUAkp32uenhZt",
        "name": "Party Monster",
        "duration": 249213,
        "artistName": "The Weeknd",
        "artistSpotifyID": "1Xyo4u8uXC1ZmMpatF05PJ",
        "features": []
      },
      {
        "spotifyID": "4oeaIftdpT3JuZLcCkKmVE",
        "name": "False Alarm",
        "duration": 220306,
        "artistName": "The Weeknd",
        "artistSpotifyID": "1Xyo4u8uXC1ZmMpatF05PJ",
        "features": []
      },
      {
        "spotifyID": "37F0uwRSrdzkBiuj0D5UHI",
        "name": "Reminder",
        "duration": 218880,
        "artistName": "The Weeknd",
        "artistSpotifyID": "1Xyo4u8uXC1ZmMpatF05PJ",
        "features": []
      },
      {
        "spotifyID": "36YCdzT57us0LhDmCYtrNE",
        "name": "Rockin’",
        "duration": 232880,
        "artistName": "The Weeknd",
        "artistSpotifyID": "1Xyo4u8uXC1ZmMpatF05PJ",
        "features": []
      },
      {
        "spotifyID": "00NAQYOP4AmWR549nnYJZu",
        "name": "Secrets",
        "duration": 265600,
        "artistName": "The Weeknd",
        "artistSpotifyID": "1Xyo4u8uXC1ZmMpatF05PJ",
        "features": []
      },
      {
        "spotifyID": "1oGdVdYjeQvojGKDddxLQQ",
        "name": "True Colors",
        "duration": 206013,
        "artistName": "The Weeknd",
        "artistSpotifyID": "1Xyo4u8uXC1ZmMpatF05PJ",
        "features": []
      },
      {
        "spotifyID": "4EDijkJdHBZZ0GwJ12iTAj",
        "name": "Stargirl Interlude",
        "duration": 111640,
        "artistName": "The Weeknd",
        "artistSpotifyID": "1Xyo4u8uXC1ZmMpatF05PJ",
        "features": [
          {
            "id": "00FQb4jTyendYWaN8pK0wa",
            "name": "Lana Del Rey"
          }
        ]
      },
      {
        "spotifyID": "4h90qkbnW1Qq6pBhoPvwko",
        "name": "Sidewalks",
        "duration": 231360,
        "artistName": "The Weeknd",
        "artistSpotifyID": "1Xyo4u8uXC1ZmMpatF05PJ",
        "features": [
          {
            "id": "2YZyLoL8N0Wb9xBt1NhZWg",
            "name": "Kendrick Lamar"
          }
        ]
      },
      {
        "spotifyID": "4mU5iXHeLgbR94siF7p1sY",
        "name": "Six Feet Under",
        "duration": 237573,
        "artistName": "The Weeknd",
        "artistSpotifyID": "1Xyo4u8uXC1ZmMpatF05PJ",
        "features": []
      },
      {
        "spotifyID": "27BgDmciSjoxTG0almHTpZ",
        "name": "Love To Lay",
        "duration": 223293,
        "artistName": "The Weeknd",
        "artistSpotifyID": "1Xyo4u8uXC1ZmMpatF05PJ",
        "features": []
      },
      {
        "spotifyID": "0ifooM33X1iBxVYyOkSbXW",
        "name": "A Lonely Night",
        "duration": 220173,
        "artistName": "The Weeknd",
        "artistSpotifyID": "1Xyo4u8uXC1ZmMpatF05PJ",
        "features": []
      },
      {
        "spotifyID": "6pDVjCUA3B1vg9waKutAsv",
        "name": "Attention",
        "duration": 197653,
        "artistName": "The Weeknd",
        "artistSpotifyID": "1Xyo4u8uXC1ZmMpatF05PJ",
        "features": []
      },
      {
        "spotifyID": "15k2nBQJ0teDmPZHrOXL2N",
        "name": "Ordinary Life",
        "duration": 221920,
        "artistName": "The Weeknd",
        "artistSpotifyID": "1Xyo4u8uXC1ZmMpatF05PJ",
        "features": []
      },
      {
        "spotifyID": "57qiTKh8bVX0VtfUNTQqhw",
        "name": "Nothing Without You",
        "duration": 198653,
        "artistName": "The Weeknd",
        "artistSpotifyID": "1Xyo4u8uXC1ZmMpatF05PJ",
        "features": []
      },
      {
        "spotifyID": "0NWqNXBJTpXbkI5rPWNy3p",
        "name": "All I Know",
        "duration": 321026,
        "artistName": "The Weeknd",
        "artistSpotifyID": "1Xyo4u8uXC1ZmMpatF05PJ",
        "features": [
          {
            "id": "1RyvyyTE3xzB2ZywiAwp0i",
            "name": "Future"
          }
        ]
      },
      {
        "spotifyID": "2Ch7LmS7r2Gy2kc64wv3Bz",
        "name": "Die For You",
        "duration": 260252,
        "artistName": "The Weeknd",
        "artistSpotifyID": "1Xyo4u8uXC1ZmMpatF05PJ",
        "features": []
      },
      {
        "spotifyID": "3dhjNA0jGA8vHBQ1VdD6vV",
        "name": "I Feel It Coming",
        "duration": 269186,
        "artistName": "The Weeknd",
        "artistSpotifyID": "1Xyo4u8uXC1ZmMpatF05PJ",
        "features": [
          {
            "id": "4tZwfgrHOc3mvqYlEYSvVi",
            "name": "Daft Punk"
          }
        ]
      }
    ]
  },
  {
    "spotifyID": "6trNtQUgC8cgbWcqoMYkOR",
    "name": "beerbongs & bentleys",
    "uri": "spotify:album:6trNtQUgC8cgbWcqoMYkOR",
    "rawReleaseDate": "2018-04-27",
    "releaseDate": "April 27th, 2018",
    "releaseYear": 2018,
    "runtime": "64 minutes 14 seconds",
    "imageURLs": [
      {
        "url": "https://i.scdn.co/image/ab67616d0000b273b1c4b76e23414c9f20242268",
        "height": 640,
        "width": 640
      },
      {
        "url": "https://i.scdn.co/image/ab67616d00001e02b1c4b76e23414c9f20242268",
        "height": 300,
        "width": 300
      },
      {
        "url": "https://i.scdn.co/image/ab67616d00004851b1c4b76e23414c9f20242268",
        "height": 64,
        "width": 64
      }
    ],
    "colors": [
      {
        "hex": "#cabf09"
      },
      {
        "hex": "#302448"
      }
    ],
    "artists": [
      {
        "spotifyID": "246dkjvS1zLTtiykXe5h60",
        "name": "Post Malone",
        "imageURLs": [
          {
            "url": "https://i.scdn.co/image/ab6761610000e5ebe17c0aa1714a03d62b5ce4e0",
            "height": 640,
            "width": 640
          },
          {
            "url": "https://i.scdn.co/image/ab67616100005174e17c0aa1714a03d62b5ce4e0",
            "height": 320,
            "width": 320
          },
          {
            "url": "https://i.scdn.co/image/ab6761610000f178e17c0aa1714a03d62b5ce4e0",
            "height": 160,
            "width": 160
          }
        ]
      }
    ],
    "tracks": [
      {
        "spotifyID": "3fpVWegR6YOS1Yk5HSMYIq",
        "name": "Paranoid",
        "duration": 221786,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "5VuxWXbt7XENQCtE9TzpTv",
        "name": "Spoil My Night (feat. Swae Lee)",
        "duration": 194560,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": [
          {
            "id": "1zNqQNIdeOUZHb8zbZRFMX",
            "name": "Swae Lee"
          }
        ]
      },
      {
        "spotifyID": "2VdT56BGpdqNHUgOe1j5vc",
        "name": "Rich & Sad",
        "duration": 206453,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "5lZZmityu9TAjNvSY6GLhR",
        "name": "Zack And Codeine",
        "duration": 204360,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "5ffntNJnJOeFv7b7DCd0Bw",
        "name": "Takin' Shots",
        "duration": 216746,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "0e7ipj03S05BNilyu5bRzt",
        "name": "rockstar (feat. 21 Savage)",
        "duration": 218146,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": [
          {
            "id": "1URnnhqYAYcrqrcwql10ft",
            "name": "21 Savage"
          }
        ]
      },
      {
        "spotifyID": "09IOPhEh1OMe0HD9b36FJk",
        "name": "Over Now",
        "duration": 246986,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "3swc6WTsr7rl9DqQKQA55C",
        "name": "Psycho (feat. Ty Dolla $ign)",
        "duration": 221440,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": [
          {
            "id": "7c0XG5cIJTrrAgEC3ULPiq",
            "name": "Ty Dolla $ign"
          }
        ]
      },
      {
        "spotifyID": "7dt6x5M1jzdTEt8oCbisTK",
        "name": "Better Now",
        "duration": 231266,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "6IaieqiCVvsNvEt6Y7yOFa",
        "name": "Ball For Me (feat. Nicki Minaj)",
        "duration": 206266,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": [
          {
            "id": "0hCNtLu0JehylgoiP8L4Gh",
            "name": "Nicki Minaj"
          }
        ]
      },
      {
        "spotifyID": "4qWCFTuNnmGNdY4egtb4ZY",
        "name": "Otherside",
        "duration": 228226,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "4H7WNRErSbONkM06blBoGc",
        "name": "Stay",
        "duration": 204426,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "1ZemPoaj7LBj1RAQrb89EC",
        "name": "Blame It On Me",
        "duration": 261799,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "688QpQAwqsLdBR6lr13wK1",
        "name": "Same Bitches (feat. G-Eazy & YG)",
        "duration": 212466,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": [
          {
            "id": "02kJSzxNuaWGqwubyUba0Z",
            "name": "G-Eazy"
          },
          {
            "id": "0A0FS04o6zMoto8OKPsDwY",
            "name": "YG"
          }
        ]
      },
      {
        "spotifyID": "0R6Jlsq25eZB3Wftpxi3oF",
        "name": "Jonestown (Interlude)",
        "duration": 112013,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "1D2L6MefbXon28PzIk9I3r",
        "name": "92 Explorer",
        "duration": 211426,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "32lItqlMi4LBhb4k0BaSaC",
        "name": "Candy Paint",
        "duration": 227533,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "0MrRAUcB8AZiB9ue2VOBYe",
        "name": "Sugar Wraith",
        "duration": 228146,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      }
    ]
  },
  {
    "spotifyID": "0S0KGZnfBGSIssfF54WSJh",
    "name": "WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",
    "uri": "spotify:album:0S0KGZnfBGSIssfF54WSJh",
    "rawReleaseDate": "2019-03-29",
    "releaseDate": "March 29th, 2019",
    "releaseYear": 2019,
    "runtime": "42 minutes 55 seconds",
    "imageURLs": [
      {
        "url": "https://i.scdn.co/image/ab67616d0000b27350a3147b4edd7701a876c6ce",
        "height": 640,
        "width": 640
      },
      {
        "url": "https://i.scdn.co/image/ab67616d00001e0250a3147b4edd7701a876c6ce",
        "height": 300,
        "width": 300
      },
      {
        "url": "https://i.scdn.co/image/ab67616d0000485150a3147b4edd7701a876c6ce",
        "height": 64,
        "width": 64
      }
    ],
    "colors": [
      {
        "hex": "#dbd1c4"
      },
      {
        "hex": "#57514d"
      }
    ],
    "artists": [
      {
        "spotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "name": "Billie Eilish",
        "imageURLs": [
          {
            "url": "https://i.scdn.co/image/ab6761610000e5eb4a21b4760d2ecb7b0dcdc8da",
            "height": 640,
            "width": 640
          },
          {
            "url": "https://i.scdn.co/image/ab676161000051744a21b4760d2ecb7b0dcdc8da",
            "height": 320,
            "width": 320
          },
          {
            "url": "https://i.scdn.co/image/ab6761610000f1784a21b4760d2ecb7b0dcdc8da",
            "height": 160,
            "width": 160
          }
        ]
      }
    ],
    "tracks": [
      {
        "spotifyID": "0rQtoQXQfwpDW0c7Fw1NeM",
        "name": "!!!!!!!",
        "duration": 13578,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "2Fxmhks0bxGSBdJ92vM42m",
        "name": "bad guy",
        "duration": 194087,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "4QIo4oxwzzafcBWkKjDpXY",
        "name": "xanny",
        "duration": 243725,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "3XF5xLJHOQQRbWya6hBp7d",
        "name": "you should see me in a crown",
        "duration": 180952,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "6IRdLKIyS4p7XNiP8r6rsx",
        "name": "all the good girls go to hell",
        "duration": 168839,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "3Fj47GNK2kUF0uaEDgXLaD",
        "name": "wish you were gay",
        "duration": 221543,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "43zdsphuZLzwA9k4DJhU0I",
        "name": "when the party's over",
        "duration": 196077,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "6X29iaaazwho3ab7GNue5r",
        "name": "8",
        "duration": 173201,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "3Tc57t9l2O8FwQZtQOvPXK",
        "name": "my strange addiction",
        "duration": 179889,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "4SSnFejRGlZikf02HLewEF",
        "name": "bury a friend",
        "duration": 193143,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "7qEKqBCD2vE5vIBsrUitpD",
        "name": "ilomilo",
        "duration": 156370,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "0tMSssfxAL2oV8Vri0mFHE",
        "name": "listen before i go",
        "duration": 242652,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "6CcJMwBtXByIz4zQLzFkKc",
        "name": "i love you",
        "duration": 291796,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      },
      {
        "spotifyID": "3LgWsmilsrWXiPYQFRD0T7",
        "name": "goodbye",
        "duration": 119409,
        "artistName": "Billie Eilish",
        "artistSpotifyID": "6qqNVTkY8uBg9cP3Jd7DAH",
        "features": []
      }
    ]
  },
  {
    "spotifyID": "4g1ZRSobMefqF6nelkgibi",
    "name": "Hollywood's Bleeding",
    "uri": "spotify:album:4g1ZRSobMefqF6nelkgibi",
    "rawReleaseDate": "2019-09-06",
    "releaseDate": "September 6th, 2019",
    "releaseYear": 2019,
    "runtime": "51 minutes 4 seconds",
    "imageURLs": [
      {
        "url": "https://i.scdn.co/image/ab67616d0000b2739478c87599550dd73bfa7e02",
        "height": 640,
        "width": 640
      },
      {
        "url": "https://i.scdn.co/image/ab67616d00001e029478c87599550dd73bfa7e02",
        "height": 300,
        "width": 300
      },
      {
        "url": "https://i.scdn.co/image/ab67616d000048519478c87599550dd73bfa7e02",
        "height": 64,
        "width": 64
      }
    ],
    "colors": [
      {
        "hex": "#2b7c8b"
      },
      {
        "hex": "#d0dce4"
      }
    ],
    "artists": [
      {
        "spotifyID": "246dkjvS1zLTtiykXe5h60",
        "name": "Post Malone",
        "imageURLs": [
          {
            "url": "https://i.scdn.co/image/ab6761610000e5ebe17c0aa1714a03d62b5ce4e0",
            "height": 640,
            "width": 640
          },
          {
            "url": "https://i.scdn.co/image/ab67616100005174e17c0aa1714a03d62b5ce4e0",
            "height": 320,
            "width": 320
          },
          {
            "url": "https://i.scdn.co/image/ab6761610000f178e17c0aa1714a03d62b5ce4e0",
            "height": 160,
            "width": 160
          }
        ]
      }
    ],
    "tracks": [
      {
        "spotifyID": "7sWRlDoTDX8geTR8zzr2vt",
        "name": "Hollywood's Bleeding",
        "duration": 156266,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "05mDaV9Vb3wrzjF6OPZnhq",
        "name": "Saint-Tropez",
        "duration": 150866,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "0Xek5rqai2jcOWCYWJfVCF",
        "name": "Enemies (feat. DaBaby)",
        "duration": 196760,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": [
          {
            "id": "4r63FhuTkUYltbVAg5TQnk",
            "name": "DaBaby"
          }
        ]
      },
      {
        "spotifyID": "1YscJ7yVTlFxW3eF6pv5ba",
        "name": "Allergic",
        "duration": 156893,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "2J0NXdHr6MYvKDSxB7k3V2",
        "name": "A Thousand Bad Times",
        "duration": 221173,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "21jGcNKet2qwijlDFuPiPb",
        "name": "Circles",
        "duration": 215280,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "2C6WXnmZ66tHhHlnvwePiK",
        "name": "Die For Me (feat. Future & Halsey)",
        "duration": 245266,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": [
          {
            "id": "26VFTg2z8YR0cCuwLzESi2",
            "name": "Halsey"
          },
          {
            "id": "1RyvyyTE3xzB2ZywiAwp0i",
            "name": "Future"
          }
        ]
      },
      {
        "spotifyID": "12Fkyg9lpmaz2zmKOfw2Y2",
        "name": "On The Road (feat. Meek Mill & Lil Baby)",
        "duration": 218320,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": [
          {
            "id": "20sxb77xiYeusSH8cVdatc",
            "name": "Meek Mill"
          },
          {
            "id": "5f7VJjfbwm532GiveGC0ZK",
            "name": "Lil Baby"
          }
        ]
      },
      {
        "spotifyID": "7CZyCXKG6d5ALeq41sLzbw",
        "name": "Take What You Want (feat. Ozzy Osbourne & Travis Scott)",
        "duration": 229573,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": [
          {
            "id": "6ZLTlhejhndI4Rh53vYhrY",
            "name": "Ozzy Osbourne"
          },
          {
            "id": "0Y5tJX1MQlPlqiwlOH1tJY",
            "name": "Travis Scott"
          }
        ]
      },
      {
        "spotifyID": "1ckLp8lCl8LipXI0ypX72m",
        "name": "I'm Gonna Be",
        "duration": 200680,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "5KE9b4x7Zj2A8XtbkqhqTe",
        "name": "Staring At The Sun (feat. SZA)",
        "duration": 168280,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": [
          {
            "id": "7tYKF4w9nC0nq9CsPZTHyP",
            "name": "SZA"
          }
        ]
      },
      {
        "spotifyID": "0RiRZpuVRbi7oqRdSMwhQY",
        "name": "Sunflower - Spider-Man: Into the Spider-Verse",
        "duration": 157560,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": [
          {
            "id": "1zNqQNIdeOUZHb8zbZRFMX",
            "name": "Swae Lee"
          }
        ]
      },
      {
        "spotifyID": "0KAzP1Rbp0Vz5pw8i1KDDI",
        "name": "Internet",
        "duration": 123386,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "0t3ZvGKlmYmVsDzBJAXK8C",
        "name": "Goodbyes (feat. Young Thug)",
        "duration": 174853,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": [
          {
            "id": "50co4Is1HCEo8bhOyUWKpn",
            "name": "Young Thug"
          }
        ]
      },
      {
        "spotifyID": "2cvOfKHOHgwQlLiuLKP2xR",
        "name": "Myself",
        "duration": 158120,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "6b2mfHMqWCA74XmUuVJm8r",
        "name": "I Know",
        "duration": 141413,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      },
      {
        "spotifyID": "7xQAfvXzm3AkraOtGPWIZg",
        "name": "Wow.",
        "duration": 149546,
        "artistName": "Post Malone",
        "artistSpotifyID": "246dkjvS1zLTtiykXe5h60",
        "features": []
      }
    ]
  },
  {
    "spotifyID": "5MS3MvWHJ3lOZPLiMxzOU6",
    "name": "Her Loss",
    "uri": "spotify:album:5MS3MvWHJ3lOZPLiMxzOU6",
    "rawReleaseDate": "2022-11-04",
    "releaseDate": "November 4th, 2022",
    "releaseYear": 2022,
    "runtime": "60 minutes 40 seconds",
    "imageURLs": [
      {
        "url": "https://i.scdn.co/image/ab67616d0000b27302854a7060fccc1a66a4b5ad",
        "height": 640,
        "width": 640
      },
      {
        "url": "https://i.scdn.co/image/ab67616d00001e0202854a7060fccc1a66a4b5ad",
        "height": 300,
        "width": 300
      },
      {
        "url": "https://i.scdn.co/image/ab67616d0000485102854a7060fccc1a66a4b5ad",
        "height": 64,
        "width": 64
      }
    ],
    "colors": [
      {
        "hex": "#501b21"
      },
      {
        "hex": "#b69daf"
      }
    ],
    "artists": [
      {
        "spotifyID": "3TVXtAsR1Inumwj472S9r4",
        "name": "Drake",
        "imageURLs": [
          {
            "url": "https://i.scdn.co/image/ab6761610000e5eb4293385d324db8558179afd9",
            "height": 640,
            "width": 640
          },
          {
            "url": "https://i.scdn.co/image/ab676161000051744293385d324db8558179afd9",
            "height": 320,
            "width": 320
          },
          {
            "url": "https://i.scdn.co/image/ab6761610000f1784293385d324db8558179afd9",
            "height": 160,
            "width": 160
          }
        ]
      },
      {
        "spotifyID": "1URnnhqYAYcrqrcwql10ft",
        "name": "21 Savage",
        "imageURLs": [
          {
            "url": "https://i.scdn.co/image/ab6761610000e5eb4f8f76117470957c0e81e5b2",
            "height": 640,
            "width": 640
          },
          {
            "url": "https://i.scdn.co/image/ab676161000051744f8f76117470957c0e81e5b2",
            "height": 320,
            "width": 320
          },
          {
            "url": "https://i.scdn.co/image/ab6761610000f1784f8f76117470957c0e81e5b2",
            "height": 160,
            "width": 160
          }
        ]
      }
    ],
    "tracks": [
      {
        "spotifyID": "1bDbXMyjaUIooNwFE9wn0N",
        "name": "Rich Flex",
        "duration": 239359,
        "artistName": "Drake",
        "artistSpotifyID": "3TVXtAsR1Inumwj472S9r4",
        "features": [
          {
            "id": "1URnnhqYAYcrqrcwql10ft",
            "name": "21 Savage"
          }
        ]
      },
      {
        "spotifyID": "46s57QULU02Voy0Kup6UEb",
        "name": "Major Distribution",
        "duration": 170501,
        "artistName": "Drake",
        "artistSpotifyID": "3TVXtAsR1Inumwj472S9r4",
        "features": [
          {
            "id": "1URnnhqYAYcrqrcwql10ft",
            "name": "21 Savage"
          }
        ]
      },
      {
        "spotifyID": "34tz0eDhGuFErIuW3q4mPX",
        "name": "On BS",
        "duration": 261543,
        "artistName": "Drake",
        "artistSpotifyID": "3TVXtAsR1Inumwj472S9r4",
        "features": [
          {
            "id": "1URnnhqYAYcrqrcwql10ft",
            "name": "21 Savage"
          }
        ]
      },
      {
        "spotifyID": "0wshkEEcJUQU33RSRBb5dv",
        "name": "BackOutsideBoyz",
        "duration": 152961,
        "artistName": "Drake",
        "artistSpotifyID": "3TVXtAsR1Inumwj472S9r4",
        "features": []
      },
      {
        "spotifyID": "7l2nxyx7IkBX5orhkALg0V",
        "name": "Privileged Rappers",
        "duration": 160821,
        "artistName": "Drake",
        "artistSpotifyID": "3TVXtAsR1Inumwj472S9r4",
        "features": [
          {
            "id": "1URnnhqYAYcrqrcwql10ft",
            "name": "21 Savage"
          }
        ]
      },
      {
        "spotifyID": "2ZL7WZcjuYKi1KUDtp4kCC",
        "name": "Spin Bout U",
        "duration": 214588,
        "artistName": "Drake",
        "artistSpotifyID": "3TVXtAsR1Inumwj472S9r4",
        "features": [
          {
            "id": "1URnnhqYAYcrqrcwql10ft",
            "name": "21 Savage"
          }
        ]
      },
      {
        "spotifyID": "0sSRLXxknVTQDStgU1NqpY",
        "name": "Hours In Silence",
        "duration": 399153,
        "artistName": "Drake",
        "artistSpotifyID": "3TVXtAsR1Inumwj472S9r4",
        "features": [
          {
            "id": "1URnnhqYAYcrqrcwql10ft",
            "name": "21 Savage"
          }
        ]
      },
      {
        "spotifyID": "4Flfb4fGscN9kXPOduQLrv",
        "name": "Treacherous Twins",
        "duration": 180098,
        "artistName": "Drake",
        "artistSpotifyID": "3TVXtAsR1Inumwj472S9r4",
        "features": [
          {
            "id": "1URnnhqYAYcrqrcwql10ft",
            "name": "21 Savage"
          }
        ]
      },
      {
        "spotifyID": "7GeTsDIc5ykNB6lORO6Cee",
        "name": "Circo Loco",
        "duration": 236795,
        "artistName": "Drake",
        "artistSpotifyID": "3TVXtAsR1Inumwj472S9r4",
        "features": [
          {
            "id": "1URnnhqYAYcrqrcwql10ft",
            "name": "21 Savage"
          }
        ]
      },
      {
        "spotifyID": "2KLwPaRDOB87XOYAT2fgxh",
        "name": "Pussy & Millions (feat. Travis Scott)",
        "duration": 242026,
        "artistName": "Drake",
        "artistSpotifyID": "3TVXtAsR1Inumwj472S9r4",
        "features": [
          {
            "id": "1URnnhqYAYcrqrcwql10ft",
            "name": "21 Savage"
          },
          {
            "id": "0Y5tJX1MQlPlqiwlOH1tJY",
            "name": "Travis Scott"
          }
        ]
      },
      {
        "spotifyID": "45pUWUeEWGoSdH6UF162G8",
        "name": "Broke Boys",
        "duration": 225439,
        "artistName": "Drake",
        "artistSpotifyID": "3TVXtAsR1Inumwj472S9r4",
        "features": [
          {
            "id": "1URnnhqYAYcrqrcwql10ft",
            "name": "21 Savage"
          }
        ]
      },
      {
        "spotifyID": "410TZrK18uRjtsTunG14cl",
        "name": "Middle of the Ocean",
        "duration": 356389,
        "artistName": "Drake",
        "artistSpotifyID": "3TVXtAsR1Inumwj472S9r4",
        "features": []
      },
      {
        "spotifyID": "2ZlABhxMMa43COmZ97kKsJ",
        "name": "Jumbotron Shit Poppin",
        "duration": 137151,
        "artistName": "Drake",
        "artistSpotifyID": "3TVXtAsR1Inumwj472S9r4",
        "features": []
      },
      {
        "spotifyID": "29YW2xXlo6Pc6M0SBTCXYN",
        "name": "More M’s",
        "duration": 221406,
        "artistName": "Drake",
        "artistSpotifyID": "3TVXtAsR1Inumwj472S9r4",
        "features": [
          {
            "id": "1URnnhqYAYcrqrcwql10ft",
            "name": "21 Savage"
          }
        ]
      },
      {
        "spotifyID": "1MTXYvJ9TSqg9x6WPCDx2n",
        "name": "3AM on Glenwood",
        "duration": 178328,
        "artistName": "21 Savage",
        "artistSpotifyID": "1URnnhqYAYcrqrcwql10ft",
        "features": []
      },
      {
        "spotifyID": "31bsuKDOzFGzBAoXxtnAJm",
        "name": "I Guess It’s Fuck Me",
        "duration": 263987,
        "artistName": "Drake",
        "artistSpotifyID": "3TVXtAsR1Inumwj472S9r4",
        "features": []
      }
    ]
  },
  {
    "spotifyID": "55huyEjfSVsk9nnmmKp5df",
    "name": "Eyes Wide Open",
    "uri": "spotify:album:55huyEjfSVsk9nnmmKp5df",
    "rawReleaseDate": "2015-04-10",
    "releaseDate": "April 10th, 2015",
    "releaseYear": 2015,
    "runtime": "40 minutes 37 seconds",
    "imageURLs": [
      {
        "url": "https://i.scdn.co/image/ab67616d0000b2735d9a77afd5c144581be1e74e",
        "height": 640,
        "width": 640
      },
      {
        "url": "https://i.scdn.co/image/ab67616d00001e025d9a77afd5c144581be1e74e",
        "height": 300,
        "width": 300
      },
      {
        "url": "https://i.scdn.co/image/ab67616d000048515d9a77afd5c144581be1e74e",
        "height": 64,
        "width": 64
      }
    ],
    "colors": [
      {
        "hex": "#5f4133"
      },
      {
        "hex": "#c8dcde"
      }
    ],
    "artists": [
      {
        "spotifyID": "74KM79TiuVKeVCqs8QtB0B",
        "name": "Sabrina Carpenter",
        "imageURLs": [
          {
            "url": "https://i.scdn.co/image/ab6761610000e5eb78e45cfa4697ce3c437cb455",
            "height": 640,
            "width": 640
          },
          {
            "url": "https://i.scdn.co/image/ab6761610000517478e45cfa4697ce3c437cb455",
            "height": 320,
            "width": 320
          },
          {
            "url": "https://i.scdn.co/image/ab6761610000f17878e45cfa4697ce3c437cb455",
            "height": 160,
            "width": 160
          }
        ]
      }
    ],
    "tracks": [
      {
        "spotifyID": "4pbrp5dxpqjfaf4GiS6YuO",
        "name": "Eyes Wide Open",
        "duration": 192720,
        "artistName": "Sabrina Carpenter",
        "artistSpotifyID": "74KM79TiuVKeVCqs8QtB0B",
        "features": []
      },
      {
        "spotifyID": "5K7fGxZQB0K5sPKhLe9e07",
        "name": "Can't Blame a Girl for Trying",
        "duration": 169306,
        "artistName": "Sabrina Carpenter",
        "artistSpotifyID": "74KM79TiuVKeVCqs8QtB0B",
        "features": []
      },
      {
        "spotifyID": "5wX5skuafFdeF31vpM6Krl",
        "name": "The Middle of Starting Over",
        "duration": 212760,
        "artistName": "Sabrina Carpenter",
        "artistSpotifyID": "74KM79TiuVKeVCqs8QtB0B",
        "features": []
      },
      {
        "spotifyID": "7lqkNvVxJdYDCSAwSJNzHs",
        "name": "We'll Be The Stars",
        "duration": 186880,
        "artistName": "Sabrina Carpenter",
        "artistSpotifyID": "74KM79TiuVKeVCqs8QtB0B",
        "features": []
      },
      {
        "spotifyID": "47hRbUwwBU3E2wyIA8OE4x",
        "name": "Two Young Hearts",
        "duration": 233600,
        "artistName": "Sabrina Carpenter",
        "artistSpotifyID": "74KM79TiuVKeVCqs8QtB0B",
        "features": []
      },
      {
        "spotifyID": "1fVnTuUKlhkFqZ6HXV56s6",
        "name": "Your Love's Like",
        "duration": 209080,
        "artistName": "Sabrina Carpenter",
        "artistSpotifyID": "74KM79TiuVKeVCqs8QtB0B",
        "features": []
      },
      {
        "spotifyID": "694MyEbGgAtoEVYqdtfvp2",
        "name": "Too Young",
        "duration": 254346,
        "artistName": "Sabrina Carpenter",
        "artistSpotifyID": "74KM79TiuVKeVCqs8QtB0B",
        "features": []
      },
      {
        "spotifyID": "75s1b4uRCk6UPOPBLNdDIA",
        "name": "Seamless",
        "duration": 186440,
        "artistName": "Sabrina Carpenter",
        "artistSpotifyID": "74KM79TiuVKeVCqs8QtB0B",
        "features": []
      },
      {
        "spotifyID": "3hqJdqziOPbu422kXaOyII",
        "name": "Right Now",
        "duration": 215226,
        "artistName": "Sabrina Carpenter",
        "artistSpotifyID": "74KM79TiuVKeVCqs8QtB0B",
        "features": []
      },
      {
        "spotifyID": "6rdKHwxWa9aqWyoGf1r20v",
        "name": "Darling I'm a Mess",
        "duration": 179053,
        "artistName": "Sabrina Carpenter",
        "artistSpotifyID": "74KM79TiuVKeVCqs8QtB0B",
        "features": []
      },
      {
        "spotifyID": "6xQdHOX1Tq3IrKsQdLs0nc",
        "name": "White Flag",
        "duration": 198386,
        "artistName": "Sabrina Carpenter",
        "artistSpotifyID": "74KM79TiuVKeVCqs8QtB0B",
        "features": []
      },
      {
        "spotifyID": "66g4mn8jSks0Hu1zEcc81G",
        "name": "Best Thing I Got",
        "duration": 199280,
        "artistName": "Sabrina Carpenter",
        "artistSpotifyID": "74KM79TiuVKeVCqs8QtB0B",
        "features": []
      }
    ]
  },
  {
    "spotifyID": "392p3shh2jkxUxY2VHvlH8",
    "name": "channel ORANGE",
    "uri": "spotify:album:392p3shh2jkxUxY2VHvlH8",
    "rawReleaseDate": "2012-07-10",
    "releaseDate": "July 10th, 2012",
    "releaseYear": 2012,
    "runtime": "55 minutes 47 seconds",
    "imageURLs": [
      {
        "url": "https://i.scdn.co/image/ab67616d0000b2737aede4855f6d0d738012e2e5",
        "height": 640,
        "width": 640
      },
      {
        "url": "https://i.scdn.co/image/ab67616d00001e027aede4855f6d0d738012e2e5",
        "height": 300,
        "width": 300
      },
      {
        "url": "https://i.scdn.co/image/ab67616d000048517aede4855f6d0d738012e2e5",
        "height": 64,
        "width": 64
      }
    ],
    "colors": [
      {
        "hex": "#2560a8"
      },
      {
        "hex": "#c9ddea"
      },
      {
        "hex": "#f37421"
      }
    ],
    "artists": [
      {
        "spotifyID": "2h93pZq0e7k5yf4dywlkpM",
        "name": "Frank Ocean",
        "imageURLs": [
          {
            "url": "https://i.scdn.co/image/ab6761610000e5ebee3123e593174208f9754fab",
            "height": 640,
            "width": 640
          },
          {
            "url": "https://i.scdn.co/image/ab67616100005174ee3123e593174208f9754fab",
            "height": 320,
            "width": 320
          },
          {
            "url": "https://i.scdn.co/image/ab6761610000f178ee3123e593174208f9754fab",
            "height": 160,
            "width": 160
          }
        ]
      }
    ],
    "tracks": [
      {
        "spotifyID": "0GAE689kVy7sFT2QWZH1Xa",
        "name": "Start",
        "duration": 45640,
        "artistName": "Frank Ocean",
        "artistSpotifyID": "2h93pZq0e7k5yf4dywlkpM",
        "features": []
      },
      {
        "spotifyID": "7DfFc7a6Rwfi3YQMRbDMau",
        "name": "Thinkin Bout You",
        "duration": 200746,
        "artistName": "Frank Ocean",
        "artistSpotifyID": "2h93pZq0e7k5yf4dywlkpM",
        "features": []
      },
      {
        "spotifyID": "6jypaMkKsoc5npsVzxhksl",
        "name": "Fertilizer",
        "duration": 39640,
        "artistName": "Frank Ocean",
        "artistSpotifyID": "2h93pZq0e7k5yf4dywlkpM",
        "features": []
      },
      {
        "spotifyID": "1HwbgJAU9PZ7YbzKgVgoIF",
        "name": "Sierra Leone",
        "duration": 148760,
        "artistName": "Frank Ocean",
        "artistSpotifyID": "2h93pZq0e7k5yf4dywlkpM",
        "features": []
      },
      {
        "spotifyID": "6MEDfjHxnVNcYmHe3mM6L2",
        "name": "Sweet Life",
        "duration": 262680,
        "artistName": "Frank Ocean",
        "artistSpotifyID": "2h93pZq0e7k5yf4dywlkpM",
        "features": []
      },
      {
        "spotifyID": "3iW3y326xuRpNVXzOMBZy5",
        "name": "Not Just Money",
        "duration": 59760,
        "artistName": "Frank Ocean",
        "artistSpotifyID": "2h93pZq0e7k5yf4dywlkpM",
        "features": []
      },
      {
        "spotifyID": "0725YWm6Z0TpZ6wrNk64Eb",
        "name": "Super Rich Kids",
        "duration": 304760,
        "artistName": "Frank Ocean",
        "artistSpotifyID": "2h93pZq0e7k5yf4dywlkpM",
        "features": [
          {
            "id": "3A5tHz1SfngyOZM2gItYKu",
            "name": "Earl Sweatshirt"
          }
        ]
      },
      {
        "spotifyID": "2ohegz9maxzroKBu9YhcCM",
        "name": "Pilot Jones",
        "duration": 184080,
        "artistName": "Frank Ocean",
        "artistSpotifyID": "2h93pZq0e7k5yf4dywlkpM",
        "features": []
      },
      {
        "spotifyID": "5lcyIeEfwZTs8Ajw3kdF7P",
        "name": "Crack Rock",
        "duration": 224146,
        "artistName": "Frank Ocean",
        "artistSpotifyID": "2h93pZq0e7k5yf4dywlkpM",
        "features": []
      },
      {
        "spotifyID": "4QhWbupniDd44EDtnh2bFJ",
        "name": "Pyramids",
        "duration": 592920,
        "artistName": "Frank Ocean",
        "artistSpotifyID": "2h93pZq0e7k5yf4dywlkpM",
        "features": []
      },
      {
        "spotifyID": "3GZD6HmiNUhxXYf8Gch723",
        "name": "Lost",
        "duration": 234093,
        "artistName": "Frank Ocean",
        "artistSpotifyID": "2h93pZq0e7k5yf4dywlkpM",
        "features": []
      },
      {
        "spotifyID": "1VMdwVq0yaTc4DeqSCi7DO",
        "name": "White",
        "duration": 76280,
        "artistName": "Frank Ocean",
        "artistSpotifyID": "2h93pZq0e7k5yf4dywlkpM",
        "features": [
          {
            "id": "0hEurMDQu99nJRq8pTxO14",
            "name": "John Mayer"
          }
        ]
      },
      {
        "spotifyID": "0msrDPXxZpts4FRnoX0bFr",
        "name": "Monks",
        "duration": 200240,
        "artistName": "Frank Ocean",
        "artistSpotifyID": "2h93pZq0e7k5yf4dywlkpM",
        "features": []
      },
      {
        "spotifyID": "2pMPWE7PJH1PizfgGRMnR9",
        "name": "Bad Religion",
        "duration": 175453,
        "artistName": "Frank Ocean",
        "artistSpotifyID": "2h93pZq0e7k5yf4dywlkpM",
        "features": []
      },
      {
        "spotifyID": "1fOkmYW3ZFkkjIdOZSf596",
        "name": "Pink Matter",
        "duration": 268813,
        "artistName": "Frank Ocean",
        "artistSpotifyID": "2h93pZq0e7k5yf4dywlkpM",
        "features": [
          {
            "id": "74V3dE1a51skRkdII8y2C6",
            "name": "André 3000"
          }
        ]
      },
      {
        "spotifyID": "4YZbVct8l9MnAVIROnLQdx",
        "name": "Forrest Gump",
        "duration": 194840,
        "artistName": "Frank Ocean",
        "artistSpotifyID": "2h93pZq0e7k5yf4dywlkpM",
        "features": []
      },
      {
        "spotifyID": "05tFLPSXJ1BbqIXy4Jeqfh",
        "name": "End",
        "duration": 134600,
        "artistName": "Frank Ocean",
        "artistSpotifyID": "2h93pZq0e7k5yf4dywlkpM",
        "features": []
      }
    ]
  },
  {
    "spotifyID": "2vlhlrgMaXqcnhRqIEV9AP",
    "name": "Dua Lipa",
    "uri": "spotify:album:2vlhlrgMaXqcnhRqIEV9AP",
    "rawReleaseDate": "2017-06-02",
    "releaseDate": "June 2nd, 2017",
    "releaseYear": 2017,
    "runtime": "40 minutes 46 seconds",
    "imageURLs": [
      {
        "url": "https://i.scdn.co/image/ab67616d0000b273b627441824c5d0748c8cb077",
        "height": 640,
        "width": 640
      },
      {
        "url": "https://i.scdn.co/image/ab67616d00001e02b627441824c5d0748c8cb077",
        "height": 300,
        "width": 300
      },
      {
        "url": "https://i.scdn.co/image/ab67616d00004851b627441824c5d0748c8cb077",
        "height": 64,
        "width": 64
      }
    ],
    "colors": [
      {
        "hex": "#551323"
      },
      {
        "hex": "#b8aeab"
      }
    ],
    "artists": [
      {
        "spotifyID": "6M2wZ9GZgrQXHCFfjv46we",
        "name": "Dua Lipa",
        "imageURLs": [
          {
            "url": "https://i.scdn.co/image/ab6761610000e5eb0c68f6c95232e716f0abee8d",
            "height": 640,
            "width": 640
          },
          {
            "url": "https://i.scdn.co/image/ab676161000051740c68f6c95232e716f0abee8d",
            "height": 320,
            "width": 320
          },
          {
            "url": "https://i.scdn.co/image/ab6761610000f1780c68f6c95232e716f0abee8d",
            "height": 160,
            "width": 160
          }
        ]
      }
    ],
    "tracks": [
      {
        "spotifyID": "2KuMEU3LN4en78qMFzOys1",
        "name": "Genesis",
        "duration": 205720,
        "artistName": "Dua Lipa",
        "artistSpotifyID": "6M2wZ9GZgrQXHCFfjv46we",
        "features": []
      },
      {
        "spotifyID": "49PFWBeOsYDd13QtM9pXzC",
        "name": "Lost In Your Light (feat. Miguel)",
        "duration": 203769,
        "artistName": "Dua Lipa",
        "artistSpotifyID": "6M2wZ9GZgrQXHCFfjv46we",
        "features": [
          {
            "id": "360IAlyVv4PCEVjgyMZrxK",
            "name": "Miguel"
          }
        ]
      },
      {
        "spotifyID": "2yGPtnlo8HWVo2LKd3MjE5",
        "name": "Hotter Than Hell",
        "duration": 187957,
        "artistName": "Dua Lipa",
        "artistSpotifyID": "6M2wZ9GZgrQXHCFfjv46we",
        "features": []
      },
      {
        "spotifyID": "1u5WAP1xPjbQu78BcoXfVx",
        "name": "Be the One",
        "duration": 202914,
        "artistName": "Dua Lipa",
        "artistSpotifyID": "6M2wZ9GZgrQXHCFfjv46we",
        "features": []
      },
      {
        "spotifyID": "0QUM7hk4Koc6oyUGKmtik9",
        "name": "IDGAF",
        "duration": 217946,
        "artistName": "Dua Lipa",
        "artistSpotifyID": "6M2wZ9GZgrQXHCFfjv46we",
        "features": []
      },
      {
        "spotifyID": "28sGFFlbg89HBUPQfIe3Cm",
        "name": "Blow Your Mind (Mwah)",
        "duration": 178583,
        "artistName": "Dua Lipa",
        "artistSpotifyID": "6M2wZ9GZgrQXHCFfjv46we",
        "features": []
      },
      {
        "spotifyID": "0lvMmDu4Vu70c3PJpx2Bf4",
        "name": "Garden",
        "duration": 227946,
        "artistName": "Dua Lipa",
        "artistSpotifyID": "6M2wZ9GZgrQXHCFfjv46we",
        "features": []
      },
      {
        "spotifyID": "589jgzHuDTw2XHzyjzsjxI",
        "name": "No Goodbyes",
        "duration": 216080,
        "artistName": "Dua Lipa",
        "artistSpotifyID": "6M2wZ9GZgrQXHCFfjv46we",
        "features": []
      },
      {
        "spotifyID": "20lPH2tJAPydGydi5xSKCT",
        "name": "Thinking 'Bout You",
        "duration": 171946,
        "artistName": "Dua Lipa",
        "artistSpotifyID": "6M2wZ9GZgrQXHCFfjv46we",
        "features": []
      },
      {
        "spotifyID": "5fVcK4ibJpRsjvG5aIYTb7",
        "name": "New Rules",
        "duration": 209320,
        "artistName": "Dua Lipa",
        "artistSpotifyID": "6M2wZ9GZgrQXHCFfjv46we",
        "features": []
      },
      {
        "spotifyID": "2nQ0nMRlMXs1drggwIDxr4",
        "name": "Begging",
        "duration": 194106,
        "artistName": "Dua Lipa",
        "artistSpotifyID": "6M2wZ9GZgrQXHCFfjv46we",
        "features": []
      },
      {
        "spotifyID": "5qKoCOV5gPKRygeanuP2Um",
        "name": "Homesick",
        "duration": 230480,
        "artistName": "Dua Lipa",
        "artistSpotifyID": "6M2wZ9GZgrQXHCFfjv46we",
        "features": []
      }
    ]
  }
];
