import { writeFileSync } from "fs";
import path from "path";
import "dotenv/config";
import { formatDate } from "@shared/helpers/formatDate";
import getTotalDuration from "@shared/helpers/formatDuration";
import { SpotifyClient } from "@/api/models/SpotifyClient";
import { SpotifyTokenCache } from "@/api/models/SpotifyTokenCache";
import { getImageColors } from "@/helpers/getImageColors";
import type { CapturedAlbum } from "./captured";

// Snapshots real album metadata from spotify into albums.ts so the
// seeder can run deterministically with no network. Re-run only when this list changes.
// The first eight ids become reviewed albums, the last two become bookmarks.
const CAPTURE_IDS = [
  "7aJuG4TFXa2hmE4z1yxc3n",
  "3HHNR44YbP7XogMVwzbodx",
  "2ODvWsOgouMbaA5xf0RkJe",
  "6trNtQUgC8cgbWcqoMYkOR",
  "0S0KGZnfBGSIssfF54WSJh",
  "4g1ZRSobMefqF6nelkgibi",
  "5MS3MvWHJ3lOZPLiMxzOU6",
  "55huyEjfSVsk9nnmmKp5df",
  "392p3shh2jkxUxY2VHvlH8",
  "2vlhlrgMaXqcnhRqIEV9AP",
];

const capture = async () => {
  const token = await SpotifyTokenCache.getAccessToken();
  const albums: CapturedAlbum[] = [];

  for (const id of CAPTURE_IDS) {
    const album = await SpotifyClient.getAlbum(id, token);
    const details = await SpotifyClient.getArtists(
      album.artists.map(artist => artist.id),
      token
    );
    const detailMap = new Map(details.map(artist => [artist.id, artist]));
    const colors = await getImageColors(album.images[0].url);

    albums.push({
      spotifyID: album.id,
      name: album.name,
      uri: album.uri,
      rawReleaseDate: album.release_date,
      releaseDate: formatDate(album.release_date),
      releaseYear: Number(album.release_date.split("-")[0]),
      runtime: getTotalDuration(album),
      imageURLs: album.images,
      colors,
      artists: album.artists.map(artist => ({
        spotifyID: artist.id,
        name: artist.name,
        imageURLs: detailMap.get(artist.id)?.images ?? [],
      })),
      tracks: album.tracks.items.map(track => ({
        spotifyID: track.id,
        name: track.name,
        duration: track.duration_ms,
        artistName: track.artists[0].name,
        artistSpotifyID: track.artists[0].id,
        features: track.artists.slice(1).map(feature => ({ id: feature.id, name: feature.name })),
      })),
    });

    console.log(`Captured ${album.name} by ${album.artists.map(artist => artist.name).join(", ")} (${album.tracks.items.length} tracks)`);
  }

  const file = `// Generated by db:capture-fixtures, do not edit by hand\nimport type { CapturedAlbum } from "./captured";\n\nexport const capturedAlbums: CapturedAlbum[] = ${JSON.stringify(albums, null, 2)};\n`;
  writeFileSync(path.join(__dirname, "albums.ts"), file);
  console.log(`Wrote ${albums.length} albums to albums.ts`);
};

capture();
