/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as AlbumsIndexImport } from './routes/albums/index'
import { Route as AlbumsAlbumIDImport } from './routes/albums/$albumID'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AlbumsIndexRoute = AlbumsIndexImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => rootRoute,
} as any)

const AlbumsAlbumIDRoute = AlbumsAlbumIDImport.update({
  id: '/albums/$albumID',
  path: '/albums/$albumID',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/albums/$albumID': {
      id: '/albums/$albumID'
      path: '/albums/$albumID'
      fullPath: '/albums/$albumID'
      preLoaderRoute: typeof AlbumsAlbumIDImport
      parentRoute: typeof rootRoute
    }
    '/albums/': {
      id: '/albums/'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/albums/$albumID': typeof AlbumsAlbumIDRoute
  '/albums': typeof AlbumsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/albums/$albumID': typeof AlbumsAlbumIDRoute
  '/albums': typeof AlbumsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/albums/$albumID': typeof AlbumsAlbumIDRoute
  '/albums/': typeof AlbumsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/albums/$albumID' | '/albums'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/albums/$albumID' | '/albums'
  id: '__root__' | '/' | '/about' | '/albums/$albumID' | '/albums/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlbumsAlbumIDRoute: typeof AlbumsAlbumIDRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlbumsAlbumIDRoute: AlbumsAlbumIDRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/albums/$albumID",
        "/albums/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/albums/$albumID": {
      "filePath": "albums/$albumID.tsx"
    },
    "/albums/": {
      "filePath": "albums/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
